import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'installation',
    'helloworld',
    {
      type: 'category',
      label: '01 - Input & Output',
      items: ['input-output/input-output'],
    },
    {
      type: 'category',
      label: '02 - Primitive Types & Operations',
      items: ['primitive-types-and-operations/variables-and-assignments',
              'primitive-types-and-operations/primitive-types',
	      'primitive-types-and-operations/operations-on-primitive-types'],
    },
    {
      type: 'category',
      label: '03 - Type System',
      items: ['type-system/type-checking',
              'type-system/type-strength'],
    },
    {
      type: 'category',
      label: '04 - Data Structures',
      items: ['data-structures/arrays',
              'data-structures/slices',
              'data-structures/maps'],
    },
    {
      type: 'category',
      label: '05 - Control Structures',
      items: ['control-structures/conditionals',
              'control-structures/loops'],
    },
    {
      type: 'category',
      label: '06 - Procedural Programming',
      items: ['procedural-programming/functions']
    },
    {
      type: 'category',
      label: '07 - User-Defined Types',
      items: ['advanced-types/types',
              'advanced-types/structs']
    },
    {
      type: 'category',
      label: '08 - Modularization',
      items: ['modularization/packages-modules'],
    },
    'what-next',
  ],
};

export default sidebars;
